# Generated by Django 5.1.2 on 2024-10-15 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("pubdate", models.DateField()),
                ("description", models.TextField()),
                ("pricesales", models.IntegerField()),
                ("pricestandard", models.IntegerField()),
                ("rating_score", models.FloatField()),
                ("rating_count", models.IntegerField()),
                (
                    "best_duration",
                    models.CharField(default="default value", max_length=200),
                ),
                ("best_rank", models.IntegerField()),
                ("publisher", models.CharField(max_length=200)),
                ("sales_point", models.IntegerField()),
                ("cover_url", models.URLField()),
                ("link", models.URLField()),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="books.author"
                    ),
                ),
            ],
        ),
    ]
