# Generated by Django 5.1.2 on 2024-10-16 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="author",
            name="description",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="author",
            name="image",
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name="author",
            name="nominated_year",
            field=models.IntegerField(null=True),
        ),
    ]
