# Generated by Django 5.1.2 on 2024-10-21 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0003_book_age_gender_ratings"),
    ]

    operations = [
        migrations.CreateModel(
            name="PublisherSalesData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("publisher", models.CharField(max_length=200)),
                ("total_sales", models.IntegerField()),
                ("book_count", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="BookAgeGenderData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("age_10", models.FloatField(default=0.0)),
                ("age_20", models.FloatField(default=0.0)),
                ("age_30", models.FloatField(default=0.0)),
                ("age_40", models.FloatField(default=0.0)),
                ("age_50", models.FloatField(default=0.0)),
                ("age_60", models.FloatField(default=0.0)),
                ("male", models.FloatField(default=0.0)),
                ("female", models.FloatField(default=0.0)),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="age_gender_data",
                        to="books.book",
                    ),
                ),
            ],
        ),
    ]
