# Generated by Django 5.1.2 on 2024-10-21 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0004_publishersalesdata_bookagegenderdata"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuthorAgeGenderData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("age_10", models.FloatField(default=0.0)),
                ("age_20", models.FloatField(default=0.0)),
                ("age_30", models.FloatField(default=0.0)),
                ("age_40", models.FloatField(default=0.0)),
                ("age_50", models.FloatField(default=0.0)),
                ("age_60", models.FloatField(default=0.0)),
                ("male", models.FloatField(default=0.0)),
                ("female", models.FloatField(default=0.0)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="age_gender_data",
                        to="books.author",
                    ),
                ),
            ],
        ),
    ]
