# Generated by Django 5.1.2 on 2024-10-21 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0005_authoragegenderdata"),
    ]

    operations = [
        migrations.CreateModel(
            name="BookSalesInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pricesales", models.IntegerField()),
                ("pricestandard", models.IntegerField()),
                ("discount_price", models.IntegerField()),
                ("discount_rate", models.FloatField()),
                ("sales_point", models.IntegerField()),
                (
                    "book",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sales_info",
                        to="books.book",
                    ),
                ),
            ],
        ),
    ]
