# Generated by Django 5.1.2 on 2024-10-21 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_booksalesinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='stock_status',
            field=models.CharField(default='', max_length=200),
        ),
    ]
